_core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

todoapp/urls.py
from django import views
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (CustomLoginView, DeleteView, RegisterPage, TaskCreate,
                    TaskDetail, TaskList, TaskReorder, TaskUpdate)

app_name = 'todoapp'

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='todoapp:login'), name='logout'), # noqa E501
    path('register/', RegisterPage.as_view(), name='register'),
    path('tasks', TaskList.as_view(), name='tasks'),
    # path('', views.Vazia, name='log'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    path('task-reorder/', TaskReorder.as_view(), name='task-reorder'),
]

todoapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = 'user'

todoapp/forms.py
from django import forms

# Reordering Form and View


class PositionForm(forms.Form):
    position = forms.CharField()

todoapp/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db import transaction
# Create your views here.
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
# Imports for Reordering Feature
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)
from django.views.generic.list import ListView

from .forms import PositionForm
from .models import Task

# def Vazia(request):
#     return render(request,'todoapp/login.html')


class CustomLoginView(LoginView):
    template_name = 'todoapp/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('todoapp:tasks')


class RegisterPage(FormView):
    template_name = 'todoapp/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todoapp:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('todoapp:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    redirect_to = 'todoapp:login'
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__contains=search_input)

        context['search_input'] = search_input

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    redirect_to = 'todoapp:login'
    model = Task
    context_object_name = 'task'
    template_name = 'todoapp/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    redirect_to = 'todoapp:login'
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todoapp:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    redirect_to = 'todoapp:login'
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todoapp:tasks')


class DeleteView(LoginRequiredMixin, DeleteView):
    redirect_to = 'todoapp:login'
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todoapp:tasks')

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(user=owner)


class TaskReorder(View):
    def post(self, request):
        form = PositionForm(request.POST)

        if form.is_valid():
            positionList = form.cleaned_data["position"].split(',')

            with transaction.atomic():
                self.request.user.set_task_order(positionList)

        return redirect(reverse_lazy('todoapp:tasks'))

todoapp/templates/todoapp/login.html
{% extends 'todoapp/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <div class="text-center">
        <br>
        <p>Ainda não tem uma conta? <a href="{% url 'todoapp:register' %}">Registre-se</a> <br>E salve suas próprias notas.</p>
        <br><br>
        <h3>Não quer criar um usuário?</h3>
        <p>
            Teste as funcionalidades com o usuário teste.
        </p>
        <a href="#" id="teste_btn">
            Clique aqui e logue automaticamente como usuario Teste
        </a>
    </div>
</div>
<br>


    
<script>
    $(function () {
        // alert("carregado");
        $('#id_username').attr('autocomplete', 'off');

        //$("#teste_btn").event.preventDefault();
        $("#teste_btn").on('click', function () {
            console.log("teste");

            $("#id_username").val("testuser2");
            $("#id_password").val("t3stU5er@");
            $( ".button" ).trigger('click');
        })




    })
</script>




{% endblock content %}

todoapp/templates/todoapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="To do list implemented using Django and adapted by Robinson as a full stack project.">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'portapp/img/faviconEnedino.svg'%}">
    <title>To Do</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link href="{% static '/todoapp/css/style.css'%}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>

</head>

<body>


    {% include 'todoapp/partials/_nav.html' %}

    <div class="appcontainer">
        {% block content %} {% endblock content %}
    </div>

    {% include 'todoapp/partials/_footer_portapp.html' %}
</body>

</html>

todoapp/templates/todoapp/partials/_footer_portapp.html
{% load static %}
	<!--================Footer Area =================-->
	<footer class="footer pt-3  ">
		<div class="container text-center">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="footer_top flex-column">
						<div class="footer_logo mt-1">
							<a href="https://www.enedino.com.br">
								<img src="{% static 'todoapp/img/logo.png'%}" alt="">
								
							</a>
							<br>
							<a class="navbar-brand logo_h" href="https://www.enedino.com.br"><img src="{% static 'todoapp/img/faviconEnedino.svg'%}" style="width:40px" alt=""></a>
						</div>
						<div class="footer_social">
                            <a class="btn btn-link btn-floating m-3 rounded-circle"
							href="https://www.enedino.com.br/contato"  role="button"><i
                                    class="fab fa-google  fa-3x"></i></a>
                            <a class="btn btn-link btn-floating m-3 rounded-circle"
                                href="https://www.linkedin.com/in/robinsonbrz" target="_blank" role="button"><i
                                    class="fab fa-linkedin-in  fa-3x"></i></a>
                            <a class="btn btn-link btn-floating m-3 rounded-circle icon-socials" href="https://github.com/robinsonbrz"
                                target="_blank" role="button"><i class="fab fa-github fa-3x"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="p-3" style="background-color: rgba(0, 0, 0, 0.2);">
				© 2022 Copyright:
				<a class="text-left text-dark" href="https://www.djangoproject.com/"  target="_blank">Powered by Django</a>
		  
				<a class="text-right text-light mr-5" href="https://www.enedino.com.br"  target="_blank">
				  <span class="text-right" >coded by Robinson</span>
				</a>
			  </div>
		</div>
	</footer>
	<!--================End Footer Area =================-->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/stellar.js/0.6.2/jquery.stellar.min.js" integrity="sha512-PNXCBnFH9wShbV+mYnrfo0Gf3iSREgBWmYAoMIfc+Z83vVq3Nu4yxBk6j+BZ40ZIhtW3WlTQdBvW3AYLAnlgpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js" integrity="sha512-IsNh5E3eYy3tr/JiX2Yx4vsCujtkhwl7SLqgnwLNgf04Hrt9BT9SXlLlZlWx+OK4ndzAoALhsMNcCmkggjZB1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" integrity="sha512-NqYds8su6jivy1/WLoW8x1tZMRD7/1ZfhWG/jcRQLOzV1k1rIODCpMgoBnar5QXshKJGV7vi0LXLNXPoFsM5Zg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/5.0.0/imagesloaded.pkgd.min.js" integrity="sha512-kfs3Dt9u9YcOiIt4rNcPUzdyNNO9sVGQPiZsub7ywg6lRW5KuK1m145ImrFHe3LMWXHndoKo2YRXWy8rnOcSKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.1/isotope.pkgd.min.js" integrity="sha512-+OO9GhDMRwCVHN/PBznZjqGWOq8FeLkLHTAdRBcbGv6PGgSpPYMsJBJKDzca6eJuAwLF7XOtoY7Ig2emcMX5zQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js" integrity="sha512-lo4YgiwkxsVIJ5mex2b+VHUKlInSK2pFtkGFRzHsAL64/ZO5vaiCPmdGP3qZq1h9MzZzghrpDP336ScWugUMTg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxchimp/1.2.0/jquery.ajaxchimp.min.js" integrity="sha512-ZkbQd6g8+JWjLU+eCQG3eGo5/8a6mbqKWX370z2lc8d5erJxeb2LbJUAkpAh7GJs3KkyqNr/rTCuw3dfIKRFIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js" integrity="sha512-emPswKmLFtjIzEQnECO0K1syIQhO9ZVE5eG+PtirksDTRPj4pDxBqnr8kF64UHO0kO/E6lYVAfCi/4X2aOk6Nw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="{% static '/portapp/js/theme.js'%}"></script>
	

todoapp/templates/todoapp/partials/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark text-dark bg-primary pc-4">
  <a class="navbar-brand logo_h" href="https://www.enedino.com.br"><img src="{% static 'todoapp/img/brand.png'%}"  alt=""></a>
  <a class="navbar-brand logo_h" href="https://www.enedino.com.br"><img src="{% static 'todoapp/img/faviconEnedino.svg'%}" style="width:40px" alt=""></a>


  
  <a class="navbar-brand pl-4" href="{% url 'todoapp:login' %}">Lista de Tarefas - Todo List</a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  
  
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item"><a class="nav-link text-dark" href="#">Portfolio Robinson</a></li>
      {% if not user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link text-dark" href="{% url 'todoapp:register' %}">Registro   </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="{% url 'todoapp:login' %}">Login</a>
      </li>
      {% endif %}
      {% if  user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link text-dark" href="{% url 'todoapp:logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled  text-dark" > <strong>{{ user.username }}</strong></a>
      </li>
      {% endif %}
      </ul>
  </div>
</nav>

todoapp/templates/todoapp/register.html
{% extends 'todoapp/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Registro</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input class="button my-3" type="submit" value="Confirma">
    </form>
    <p>Ainda não tem uma conta? <a href="{% url 'todoapp:login' %}">Login</a></p>
</div>




{% endblock content %}

todoapp/templates/todoapp/task.html
<h1>Task: {{task}}</h1>

todoapp/templates/todoapp/task_confirm_delete.html
{% extends 'todoapp/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'todoapp:tasks' %}">&#8592; Voltar</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Deseja mesmo deletar? <b>"{{task}}"</b> </p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>



{% endblock content %}

todoapp/templates/todoapp/task_form.html
{% extends 'todoapp/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'todoapp:tasks' %}">&#8592; Voltar</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Confirma">
    </form>
</div>


{% endblock content %}

todoapp/templates/todoapp/task_list.html
{% extends 'todoapp/main.html' %} {% block content %}

<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<div class="header-bar">
    <div>
        <h1>Olá {{request.user|title}}</h1>
        <h3 style="margin:0">Você tem <i>{{count}}</i> tarefas incompleta{{ count|pluralize:"s" }}</h3>

<br>
        <ul class="list-group">
            <h3>Operações disponíves</h3>
            <li class="list-group-item">Inserir novas tarefas</li>
            <li class="list-group-item">Deletar tarefas</li>
            <li class="list-group-item">Reordenar a fila de tarefas, arrastando</li>
          </ul>

    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'todoapp:logout' %}">Logout</a> {% else %}
    <a href="{% url 'todoapp:login' %}">Login</a> {% endif %}
</div>


<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input type='text' name='search-area' placeholder="Pesquisar em tarefas" value="{{search_input}}">
        <input class="button" type="submit" value='Pesquisa'>
    </form>
    {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'todoapp:task-create' %}">&#x2b;</a>
    {% endif %}
</div>


<!-- Hidden form. Form submits new item positions -->
<form style="display: none;" id="reorderForm" method="post" action="{% url 'todoapp:task-reorder' %}">
    {% csrf_token %}
    <input type="hidden" id="positionInput" name="position">
</form>


<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.complete %}
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'todoapp:task-update' task.id %}">{{task}}</a></s></i> {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'todoapp:task-update' task.id %}">{{task}}</a> {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'todoapp:task-delete' task.id %}">&#215;</a>
            <span class="handle">&nbsp;&#10247;</span>
        </div>
    </div>

    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h3>Nenhuma nova tarefa foi criada.</h3>
        <h3>Crie uma <a style="text-decoration: none; color: #e53935;" href="{% url 'todoapp:task-create' %}">Nova tarefa</a> ! </h3>
    </div>
    {% endfor %}
</div>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("reorderForm");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',

    });

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');
        reorderForm.submit();
    }

    document.ondrop = reordering
</script>

{% endblock content %}